general {
    lock_cmd = /home/tom/git/dotfiles/hypr/oled-lock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 1200
    on-timeout = loginctl lock-session
}
