general {
    lock_cmd = pidof swaylock || swaylock -f -c 080d12 --indicator-radius 120 --indicator-thickness 8 --inside-color 080d12dd --ring-color 33ccffee --key-hl-color 00ff99ee --bs-hl-color ff4d6dee --text-color e8f5f8ff --line-color 00000000 --separator-color 00000000
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 1200
    on-timeout = loginctl lock-session
}
